name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:

    - name: Install test dependencies
      run: pip install pytest

    - name: Run pytest
      run: pytest tests/
      
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: sudo docker build -t sampleapp:latest .

    - uses: actions/checkout@v4
    - name: run the the Docker container
      run: sudo docker run -d --name my_sample_app -p 5000:5000 sampleapp:latest

