name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks Secret Scan
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: gitleaks.toml
          verbose: true
          redact: true
          exit-zero: false

  build_docker:
    runs-on: self-hosted
    needs: gitleaks
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t sampleapp:latest .

  save_tarball:
    runs-on: self-hosted
    needs: build_docker
    steps:
    - uses: actions/checkout@v4
    - name: Save Docker image as tarball
      run: docker save -o sampleapp.tar sampleapp:latest
    - name: Upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: sampleapp-tar
        path: sampleapp.tar

  trivy_scan:
    runs-on: self-hosted
    needs: save_tarball
    steps:
    - uses: actions/checkout@v4
    - name: Download Docker tarball
      uses: actions/download-artifact@v4
      with:
        name: sampleapp-tar
        path: .
    - name: Run Trivy vulnerability scanner
      run: trivy image --input sampleapp.tar --exit-code 0 --severity HIGH,CRITICAL


  run_container:
    runs-on: self-hosted
    needs: trivy_scan
    steps:
      - uses: actions/checkout@v4
      - name: Run the Docker container
        run: |
          docker rm -f my_sample_app || true
          docker run -d --name my_sample_app -p 5000:5000 sampleapp:latest
